version: 0.0

os: linux

files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:

  BeforeInstall:
    - location: scripts/preinstall.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/postinstall.sh
      timeout: 1000
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root